version: "3.8"
services:
  ecommerce-psql:
    image: shimunmatic/ecommerce-db:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - db.env
    networks:
      - ecommerce-network
    volumes:
      - db-data:/var/lib/postgresql/data

  ecommerce-pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - 5050:80
    env_file:
      - pgadmin.env
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - ecommerce-network

  #  ecommerce-item:
  #   image: docker-registry.shimunmatic.de/e-commerce-item:latest
  #   restart: unless-stopped
  #  ports:
  #   - 8080:7110
  # networks:
  #   - ecommerce-network
  # environment:
  #   - SPRING_DATASOURCE_URL=jdbc:postgresql://ecommerce-psql/db_ecommerce

  ecommerce-media:
    image: e-commerce-media:latest
    restart: unless-stopped
    ports:
      - 7120:8080
    networks:
      - ecommerce-network
    volumes:
      - media-test:/data

  ecommerce-gateway:
    image: e-commerce-gateway:latest
    restart: unless-stopped
    ports:
      - 7100:8080
    networks:
      - ecommerce-network
    environment:
      - GATEWAY_URI_API-ITEM=http://172.17.0.1:7110
      - GATEWAY_URI_API-MEDIA=http://ecommerce-media
      - GATEWAY_URI_API-CDN=http://ecommerce-cdn

  ecommerce-cdn:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 7121:80
    networks:
      - ecommerce-network
    volumes:
      - media-test:/data
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  media-test:
  db-data:

networks:
  ecommerce-network:
